language: python
python: 
  - "2.7"
  - "3.5"
  - "3.6"
services:
  - docker
before_install:
  - docker build -t "webserver" -f docker/Dockerfile docker
  - docker run -d -p 80:80 webserver 
install:
  - pip install -r tests/requirements.txt
script:
  - pytest tests
