language: python
python: 
  - "2.7"
  - "3.6"
services:
  - docker
before_install:
  - docker build -t "webserver" -f docker/apache_server/Dockerfile docker/apache_server
  - docker run -d -p 80:80 webserver
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install -r tests/requirements.txt
script:
  - pytest tests
