language: python
python: 
  - "2.7"
  - "3.6"
services:
  - docker
before_install:
  - docker-compose -p project -f docker/docker-compose.yaml up --build
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install -r tests/requirements.txt
script:
  - pytest tests
