version: '3'
services:
  db:
    build: ./db
    container_name: db
    expose:
      - 3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=brickflix
      - MYSQL_USER=php
      - MYSQL_PASSWORD=SuperSecretPassword

  www:
    build: ./www
    container_name: www
    ports:
      - "80:80"
    depends_on:
      - db
