# General docker-compose file for the current system topology

version: '3'
services:
#  backend:
#    build: ./backend
#    container_name: backend
#    restart: always
#    expose:
#      - 80
#      - 3306

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    expose:
      - 80
#    depends_on:
#      - backend
