# General docker-compose file for the current system topology

version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - 8000

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
