# General docker-compose file for the current system topology

version: '3'
services:
  backend:
    build: ./db
    container_name: db
    expose:
      - 3306

  frontend:
    build: ./www
    container_name: www
    ports:
      - "80:80"
    depends_on:
      - db
