# General docker-compose file for the current system topology

version: '3'
services:
#  backend:
#    build: ./backend
#    container_name: backend
#    restart: always
#    ports:
#      - "3306:3306"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
#    depends_on:
#      - backend
